// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecipeHub.Persistence;

#nullable disable

namespace RecipeHub.Persistence.Migrations
{
    [DbContext(typeof(RecipeHubContext))]
    [Migration("20250221025723_ChangeFkReq")]
    partial class ChangeFkReq
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecipeHub.Domain.Models.Image", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("RecipeHub.Domain.Models.Ingredient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecipeId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("RecipeHub.Domain.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ImageId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("ImageId")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("RecipeHub.Domain.Models.Recipe", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("CookingTime")
                        .HasColumnType("interval");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RecipeImageId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("Name");

                    b.HasIndex("RecipeImageId")
                        .IsUnique();

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("RecipeHub.Domain.Models.RecipeStep", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("ImageId")
                        .HasColumnType("text");

                    b.Property<string>("RecipeId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ImageId")
                        .IsUnique();

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeStep", (string)null);
                });

            modelBuilder.Entity("RecipeHub.Domain.Models.Image", b =>
                {
                    b.OwnsOne("RecipeHub.Domain.Models.FilePath", "Path", b1 =>
                        {
                            b1.Property<string>("ImageId")
                                .HasColumnType("text");

                            b1.Property<string>("PathLocation")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<string>("Server")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.HasKey("ImageId");

                            b1.ToTable("Images");

                            b1.WithOwner()
                                .HasForeignKey("ImageId");
                        });

                    b.Navigation("Path");
                });

            modelBuilder.Entity("RecipeHub.Domain.Models.Ingredient", b =>
                {
                    b.HasOne("RecipeHub.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeHub.Domain.Models.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("RecipeHub.Domain.Models.Measure", "Measure", b1 =>
                        {
                            b1.Property<string>("IngredientId")
                                .HasColumnType("text");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision");

                            b1.HasKey("IngredientId");

                            b1.ToTable("Ingredients");

                            b1.WithOwner()
                                .HasForeignKey("IngredientId");
                        });

                    b.Navigation("Measure")
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RecipeHub.Domain.Models.Product", b =>
                {
                    b.HasOne("RecipeHub.Domain.Models.Image", "Image")
                        .WithOne()
                        .HasForeignKey("RecipeHub.Domain.Models.Product", "ImageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Image");
                });

            modelBuilder.Entity("RecipeHub.Domain.Models.Recipe", b =>
                {
                    b.HasOne("RecipeHub.Domain.Models.Image", "RecipeImage")
                        .WithOne()
                        .HasForeignKey("RecipeHub.Domain.Models.Recipe", "RecipeImageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("RecipeImage");
                });

            modelBuilder.Entity("RecipeHub.Domain.Models.RecipeStep", b =>
                {
                    b.HasOne("RecipeHub.Domain.Models.Image", "Image")
                        .WithOne()
                        .HasForeignKey("RecipeHub.Domain.Models.RecipeStep", "ImageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RecipeHub.Domain.Models.Recipe", null)
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Image");
                });

            modelBuilder.Entity("RecipeHub.Domain.Models.Recipe", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
